[package]
name = "serduck"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
anyhow = "1.0.48"
protobuf = "2"
signal-hook = "0.3.10"
clap = "2.33.3"